LOG_LEVEL: DEBUG
HOST: 127.0.0.1
PORT: 8000
# ######################################################################################################
# # https://docs.sqlalchemy.org/en/13/core/engines.html
DATABASE:
  DRIVER: mysql
  NAME: db_blog
  HOST: 127.0.0.1
  PORT: 3306
  USERNAME: fakeusr
  PASSWORD: fakepw
  QUERY:
    charset: utf8mb4